name: dominiqli
favicon: null
layout_spectrum: 0.75177
typography_spectrum: 0.94451
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#272121'
    - '#353034'
    - '#100a0a'
    - '#3d3c41'
    - '#4e494b'
  brandStrength: 0.5
  lightness: 0.749375787563622
  saturation: 0.5
  rhythmicContrast: 0.920126770157367
purpose: []
