name: dominiqli
favicon: null
layout_spectrum: 0.3974447827786207
typography_spectrum: 0.7082570700440556
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#E0FBFC'
    - '#C2DFE3'
    - '#9DB4C0'
    - '#5C6B73'
    - '#253237'
  brandStrength: 0.8920563419815153
  lightness: 0.749375787563622
  saturation: 0.465657397871837
  rhythmicContrast: 0.920126770157367
purpose: []
